name: fml
dependencies:
  - git
  - python=3.8
  - pip
  - scipy
  - numpy
  - matplotlib
  - flake8
  - sphinx
  - pip:
    - scikit-learn
    - pygame
    - tqdm
    - pylint
    - tensorflow==2.4.1
    - tf-agents
